"use client";
import { useState, useTransition } from "react";
import { updateClinic } from "@/lib/actions/clinic";
const DAYS = [["monday","Lunes"],["tuesday","Martes"],["wednesday","Miercoles"],["thursday","Jueves"],["friday","Viernes"],["saturday","Sabado"],["sunday","Domingo"]] as const;
type Props = { clinic: { name: string; phone: string; timezone: string; duration: number; openingHours: unknown }; editable: boolean };
export function ClinicForm({ clinic, editable }: Props) {
  const hours = clinic.openingHours as Record<string, string[]>; const [result, setResult] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  return <form className="rounded-2xl border border-slate-200 bg-white p-5" action={(data) => startTransition(async () => { const days = Object.fromEntries(DAYS.map(([key]) => [key, { enabled: data.get(`${key}-enabled`) === "on", open: String(data.get(`${key}-open`)), close: String(data.get(`${key}-close`)) }])); const response = await updateClinic({ name: String(data.get("name")), phone: String(data.get("phone")), timezone: String(data.get("timezone")), defaultAppointmentDuration: Number(data.get("duration")), days }); setResult(response.ok ? "Cambios guardados." : response.message); })}>
    <div className="flex items-center justify-between"><h2 className="font-semibold">Clinica y agenda</h2>{!editable && <span className="text-xs text-slate-500">Solo lectura</span>}</div><fieldset disabled={!editable || pending} className="mt-4 space-y-4 disabled:opacity-70"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm">Nombre<input name="name" defaultValue={clinic.name} required className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" /></label><label className="text-sm">Telefono<input name="phone" defaultValue={clinic.phone} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" /></label><label className="text-sm">Zona horaria<input name="timezone" defaultValue={clinic.timezone} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" /></label><label className="text-sm">Duracion del turno (min)<input name="duration" type="number" min="10" max="180" defaultValue={clinic.duration} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" /></label></div><div><p className="mb-2 text-sm font-medium">Horarios de atencion</p><div className="space-y-2">{DAYS.map(([key,label]) => { const value=hours[key] ?? ["09:00","18:00"]; return <div key={key} className="grid grid-cols-[1fr_auto_auto] items-center gap-2 rounded-xl bg-slate-50 p-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name={`${key}-enabled`} defaultChecked={Boolean(hours[key])} />{label}</label><input aria-label={`Apertura ${label}`} name={`${key}-open`} type="time" defaultValue={value[0]} className="rounded-lg border border-slate-200 p-2 text-sm"/><input aria-label={`Cierre ${label}`} name={`${key}-close`} type="time" defaultValue={value[1]} className="rounded-lg border border-slate-200 p-2 text-sm"/></div>})}</div></div>{editable && <button className="h-11 rounded-xl bg-emerald-600 px-5 text-sm font-medium text-white" disabled={pending}>{pending ? "Guardando..." : "Guardar cambios"}</button>}</fieldset>{result && <p className="mt-3 text-sm text-slate-600">{result}</p>}</form>;
}


