import Link from "next/link";
import { requireSession } from "@/lib/auth/session";
import { getPrisma } from "@/lib/prisma";
import { MessageComposer } from "./message-composer";
import { openConversation, resolveConversation } from "@/lib/actions/messages";

const labels = { AUTOMATED: "Bot", REQUIRES_HUMAN: "Requiere atencion", HUMAN_ACTIVE: "En atencion", RESOLVED: "Resuelta" };
export default async function MensajesPage({ searchParams }: { searchParams: Promise<{ conversation?: string; status?: string }> }) {
  const session = await requireSession(); const query = await searchParams;
  const valid = ["AUTOMATED","REQUIRES_HUMAN","HUMAN_ACTIVE","RESOLVED"].includes(query.status ?? "") ? query.status : undefined;
  const conversations = await getPrisma().whatsappConversation.findMany({ where: { clinicId: session.clinicId, ...(valid ? { status: valid as "AUTOMATED" } : {}) }, include: { client: true, assignedUser: true, messages: { orderBy: { createdAt: "asc" }, take: 100 } }, orderBy: { lastMessageAt: "desc" }, take: 50 });
  const selected = conversations.find((item) => item.id === query.conversation) ?? conversations[0];
  return <div className="grid min-h-[calc(100vh-65px)] lg:grid-cols-[360px_1fr]"><aside className="border-r border-slate-200 bg-white"><div className="p-4"><h1 className="text-xl font-semibold">Mensajes</h1><div className="mt-3 flex flex-wrap gap-2">{[["","Todas"],["REQUIRES_HUMAN","Pendientes"],["HUMAN_ACTIVE","En atencion"],["RESOLVED","Resueltas"]].map(([value,label]) => <Link key={value} href={`/mensajes${value ? `?status=${value}` : ""}`} className={`rounded-full px-3 py-1 text-xs ${query.status === value || (!query.status && !value) ? "bg-emerald-600 text-white" : "bg-slate-100"}`}>{label}</Link>)}</div></div><div className="divide-y divide-slate-100">{conversations.map((conversation) => <Link key={conversation.id} href={`/mensajes?conversation=${conversation.id}${query.status ? `&status=${query.status}` : ""}`} className={`block p-4 ${selected?.id === conversation.id ? "bg-emerald-50" : "hover:bg-slate-50"}`}><div className="flex justify-between gap-2"><span className="truncate text-sm font-medium">{conversation.contactName || conversation.client?.name || conversation.phone}</span>{conversation.unreadCount > 0 && <span className="rounded-full bg-emerald-600 px-2 text-xs text-white">{conversation.unreadCount}</span>}</div><p className="mt-1 truncate text-xs text-slate-500">{labels[conversation.status]}</p></Link>)}</div></aside>
    <section className="flex min-h-[70vh] flex-col bg-slate-50">{selected ? <><header className="flex items-center justify-between border-b border-slate-200 bg-white p-4"><div><h2 className="font-semibold">{selected.contactName || selected.client?.name || selected.phone}</h2><p className="text-xs text-slate-500">{selected.phone} - {labels[selected.status]}</p></div><div className="flex gap-2">{selected.status === "REQUIRES_HUMAN" && <form action={openConversation.bind(null, selected.id)}><button className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-medium text-white">Tomar conversacion</button></form>}{selected.status !== "RESOLVED" && <form action={resolveConversation.bind(null, selected.id)}><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-medium">Resolver</button></form>}</div></header><div className="flex-1 space-y-3 overflow-y-auto p-4 lg:p-6">{selected.messages.map((message) => <div key={message.id} className={`flex ${message.direction === "OUTBOUND" ? "justify-end" : "justify-start"}`}><div className={`max-w-[80%] whitespace-pre-wrap rounded-2xl px-4 py-2 text-sm ${message.direction === "OUTBOUND" ? "bg-emerald-600 text-white" : "border border-slate-200 bg-white"}`}>{message.content}<div className={`mt-1 text-[10px] ${message.direction === "OUTBOUND" ? "text-emerald-100" : "text-slate-400"}`}>{message.status}</div></div></div>)}</div><MessageComposer conversationId={selected.id} disabled={selected.status === "RESOLVED" || selected.status === "AUTOMATED"} /></> : <div className="grid flex-1 place-items-center text-sm text-slate-500">No hay conversaciones.</div>}</section></div>;
}



